In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 3.5 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.5 MB 3.9 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.5 MB 4.1 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.5 MB 4.2 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.5 MB 4.5 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.5 MB 4.7 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.5 MB 5.0 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.5 MB 5.3 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.5 MB 5.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.5 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 5.7 MB/s  0:00:02



[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\chitr\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [4]:
pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----------------------- ---------------- 1.0/1.8 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 4.6 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 26.1.1
    Uninstalling pip-26.1.1:
      Successfully uninstalled pip-26.1.1
Note: you may need to restart the kernel to use updated packages.


In [12]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\chitr\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip


In [11]:
import sys
print(sys.executable)

c:\Users\chitr\AppData\Local\Programs\Python\Python314\python.exe


In [13]:
import sys
print(sys.executable)
print(sys.version)

c:\Users\chitr\AppData\Local\Programs\Python\Python314\python.exe
3.14.5 (tags/v3.14.5:5607950, May 10 2026, 10:43:50) [MSC v.1944 64 bit (AMD64)]


In [14]:
import sys
!{sys.executable} -m pip install numpy

  Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)


In [15]:
import numpy as np
print(np.__version__)

2.4.6


In [2]:
import numpy as np

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [18]:
a = [1,2,3,4,5]
n = np.array(a)

In [ ]:
n ** 2 ##element wise operation


array([ 1,  4,  9, 16, 25])

In [20]:
l = range(11101010)

In [21]:
%timeit [i**2 for i in l]

624 ms ± 12.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
l_np = np.arange(100000)
l_np
len(l_np)

100000

In [ ]:
##for elemert wise operstion numpy provide cleans syntax and computational benefit
#numerical libarary

In [4]:
a = np.array([1,2,3,4])

In [6]:
a**2

array([ 1,  4,  9, 16])

In [7]:
a.ndim ##tells the diemansion
a.shape ##no of elemets acrooss a dimension
# print(len(a))

(4,)

In [ ]:
np.arange(1,4) ##same as range in python

array([1, 2, 3])

In [ ]:
np.arange(1,5,2)
np.arange(1,5,0.5) ##can have float step size

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [40]:
##start, end, count
np.linspace(1,10,5) ####1 se 10 mai kaha kaha flag lagayege ki 5 flag la jaye, end pint include hota hia
np.linspace(1,10,2)

array([ 1., 10.])

In [42]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
# arr2 = np.array([1,2,3,4.0])  ##3stores samr type of data
arr2 = np.array([1,2,3,4], dtype='float') ##or
print(arr2)

[1. 2. 3. 4.]


In [48]:
arrr = np.array([1,2,3,4,'3'])
print(arrr)

['1' '2' '3' '4' '3']


In [10]:
l2 = np.array([[1,2,3],[4,5,6],[1,2,3]])
np.ndim(l2)
l2.shape

(3, 3)

In [19]:
a = np.array([1,2,3,4,5,6],ndmin=2)
print(a)
a.shape 

# a = np.array([1,2,3,4,5,6],ndmin=2)
# a

[[1 2 3 4 5 6]]


(1, 6)

In [ ]:
##sequence of numbers
n = np.arange(1,11)
n.reshape(2,5) ##2 tells np of row, 5 is no of elemetsin each row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
a = np.array([1,2,3,4])
a.reshape(2,2)


array([[1, 2],
       [3, 4]])

In [69]:
a = np.arange(4)
np.resize(a,(2,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.resize(a,(3,5)) ##re sizes the array

array([[0, 1, 2, 3, 0],
       [1, 2, 3, 0, 1],
       [2, 3, 0, 1, 2]])

In [74]:
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
a.T ###transpose

array([0, 1, 2])

In [21]:
##flatteing an n-d array
a = np.arange(10).reshape(2,5)
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a.flatten()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
b= a.reshape(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
a.reshape(5,-1) ##  -1 to figure out col by its own

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
# a.reshape(-1,2 )
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
np.zeros([2,3])
# np.ones(2)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
a = np.diag([1,2,3])
# b = np.diag(a)
# print(b)
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np.identity(5) ##5 is no of rows

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
nq = np.array([1,2,3,4,5])
# nq[[3,4,0,2,1]] ###diplay by indes
nq[[0,3]]

array([1, 4])

In [105]:
m1 = np.arange(8).reshape(2,4)
m1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [106]:
m1[[0,0,0,1],[0,1,1,2]]

array([0, 1, 1, 6])

In [107]:
n1 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
n1[0,1:3]

array([1, 2])

In [ ]:
##[[2,3],[6,7],[10,11]]
n1[0:3,2:4]
#or
n1[0:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [31]:
a = np.arange(10)
# a[:4] = 10
a[2:6] = 2
a

array([0, 1, 2, 2, 2, 2, 6, 7, 8, 9])

In [124]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:] = b[::-1]
a



array([1, 2, 6, 7, 8])

In [ ]:
m1 = np.arange(10).reshape(2,5)
m1
m1 < 6 ##masking

# m1[m1<6]

# m1[m1%2 == 0] ##filtering

# m1[(m1%2 == 0) | (m1%5 == 0)]


array([0, 2, 4, 6, 8])

In [43]:
a = np.arange(6)
mask = (a%2 == 0)
print(mask)
a[mask] = -1
print(a)

[ True False  True False  True False]
[-1  1 -1  3 -1  5]


In [45]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a+b)

[2 4 6]
