### Universal Functions

In [ ]:
##Universal functions
##vectorised fuctios
##Agregate function
#Logical functions


In [ ]:
import numpy as np

###agretate and reduction functions

In [3]:
a = np.array([1,2])
b = np.array([1,2])
a+b

array([2, 4])

In [9]:
a = np.arange(12).reshape(3,4)
print(a)
# np.sum(a)

##calculation the sum in different dimensions, accorss the row, col etss
a.shape ##it says across first dimension it has 3 elkeemts and 2nd dimension we have 4 elements


#exmpale sum in cols wise
np.sum(a,axis=0) ##sum is happening 0 axis downwords direction
np.sum(a,axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [12]:
np.mean(a,axis=1)
np.min(a,axis=0)

array([0, 1, 2, 3])

In [ ]:
###Logical Functions:
a = np.array([0,0]) ##return true if any number is non zero
np.any(a)


np.False_

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
a<b

np.any(a<b) ##kya koi esa no hai jo is conf=diton ko true karta hia

np.True_

In [ ]:
a = np.array([1,2,1,0])
b = np.array([4,3,2,1])
np.all(a<b)  

##we use & in numpy becoz it is written in c


np.True_

In [ ]:
##sorting fucntions:::

a = np.array([1,4,7,3,6,9])
np.sort(a)
np.argsort(a) ##returns indexxx


array([0, 3, 1, 4, 2, 5])

In [27]:
a = np.array([[1,4,6],[7,5,8],[6,8,7]]) ##by deaults it get sorted in last dimentsion wchih is 1
np.sort(a)

array([[1, 4, 6],
       [5, 7, 8],
       [6, 7, 8]])

In [30]:
pip install pandas

  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 3.5 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 4.4 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/9.9 MB 5.5 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 5.9 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/9.9 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 6.2 MB/s  0:00:01

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   --------------

In [40]:
import numpy as np
h = np.loadtxt('../steps_tracker_dataset (1).txt',dtype="str",skiprows=1)
print(h)

[['08/10/2022' '4147' '3.11' '124.41' '41' '10.5' '3.77' 'stressed']
 ['11/06/2022' '323' '0.24' '9.69' '3' '6' '1.9' 'sad']
 ['28/01/2022' '6622' '4.97' '198.66' '66' '6' '4.48' 'sad']
 ['23/03/2022' '11136' '8.35' '334.08' '111' '8' '1.08' 'tired']
 ['20/05/2022' '2718' '2.04' '81.54' '27' '4.9' '1' 'tired']
 ['26/12/2022' '4972' '3.73' '149.16' '50' '6' '3.33' 'happy']
 ['27/07/2022' '15271' '11.45' '458.13' '153' '3.4' '0.88' 'happy']
 ['13/07/2022' '17290' '12.97' '518.7' '173' '11.6' '4.08' 'energetic']
 ['17/06/2022' '1042' '0.78' '31.26' '10' '6.5' '2.49' 'happy']
 ['25/06/2022' '6818' '5.11' '204.54' '68' '6.5' '3.61' 'stressed']
 ['16/01/2022' '13141' '9.86' '394.23' '131' '6.5' '2.35' 'tired']
 ['16/06/2022' '5046' '3.78' '151.38' '50' '6' '4.03' 'happy']
 ['30/10/2022' '11615' '8.71' '348.45' '116' '7.8' '0.43' 'stressed']
 ['22/08/2022' '4301' '3.23' '129.03' '43' '9' '2.87' 'happy']
 ['22/07/2022' '8655' '6.49' '259.65' '87' '9' '0.94' 'happy']
 ['08/09/2022' '14113' '10.

In [4]:
h.ndim

2

In [ ]:
h.shape

(49, 8)

In [41]:
##extract coloumns
h.T[0]



array(['08/10/2022', '11/06/2022', '28/01/2022', '23/03/2022',
       '20/05/2022', '26/12/2022', '27/07/2022', '13/07/2022',
       '17/06/2022', '25/06/2022', '16/01/2022', '16/06/2022',
       '30/10/2022', '22/08/2022', '22/07/2022', '08/09/2022',
       '09/07/2022', '04/04/2022', '26/01/2022', '24/01/2022',
       '28/07/2022', '09/02/2022', '06/08/2022', '31/10/2022',
       '26/03/2022', '19/05/2022', '10/05/2022', '13/05/2022',
       '13/06/2022', '24/07/2022', '01/02/2022', '23/01/2022',
       '08/05/2022', '07/03/2022', '20/08/2022', '20/09/2022',
       '01/08/2022', '26/07/2022', '07/07/2022', '23/01/2022',
       '17/08/2022', '01/03/2022', '22/04/2022', '14/12/2022',
       '03/03/2022', '21/05/2022', '11/01/2022', '06/03/2022',
       '29/08/2022'], dtype='<U10')

In [42]:
date,steps,distance_km,calories_burned,active_minutes,sleep_hours,water_intake_liters,mood = h.T


In [43]:
print(mood)

['stressed' 'sad' 'sad' 'tired' 'tired' 'happy' 'happy' 'energetic'
 'happy' 'stressed' 'tired' 'happy' 'stressed' 'happy' 'happy' 'stressed'
 'energetic' 'sad' 'stressed' 'sad' 'happy' 'energetic' 'tired' 'stressed'
 'sad' 'energetic' 'sad' 'stressed' 'sad' 'happy' 'stressed' 'stressed'
 'energetic' 'stressed' 'tired' 'tired' 'sad' 'tired' 'tired' 'stressed'
 'stressed' 'energetic' 'energetic' 'tired' 'happy' 'tired' 'energetic'
 'stressed' 'stressed']


In [38]:
calories_burned = np.array(calories_burned).astype(float)
sleep_hours = np.array(sleep_hours, dtype='float')
water_intake_liters = np.array(water_intake_liters, dtype='float')
distance_km = np.array(distance_km,dtype='float')
active_minutes = np.array(active_minutes).astype(int)
steps = np.array(steps).astype(int)
mood = np.array(mood).astype(str)

NameError: name 'calories_burned' is not defined

In [44]:
print(steps_distance_km)

NameError: name 'steps_distance_km' is not defined

In [ ]:
np.unique(mood)

array(['energetic', 'happy', 'sad', 'stressed', 'tired'], dtype='<U10')

In [48]:
##replacing numbers with string
# mood[mood == 'energetic'] = 300
# mood[mood == 'happy'] = 200
# mood[mood == 'sad'] = 100
# mood[mood == 'tired'] = 50
# mood[mood == 'stressed'] = 10
mood == 'happy'


array([False, False, False, False, False,  True,  True, False,  True,
       False, False,  True, False,  True,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False])

In [11]:
active_minutes[active_minutes < 100] = '0'
active_minutes[active_minutes >= 100] = '1'
active_minutes


array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0])

In [12]:
np.mean(steps)

np.float64(9590.877551020409)

In [13]:
# intmx = np.max(steps)

# for i in range(len(steps)):
#     for i in range(len(date)):
#         if steps[i] == intmx:
#            print(date[i])


max_steps = np.argmax(steps)
ans = date[max_steps]
print(ans)



21/05/2022


In [14]:
##what is the most frequent mood.
len(mood[mood == 'happy'])



9

In [15]:
np.unique(mood,return_counts=True)

(array(['energetic', 'happy', 'sad', 'stressed', 'tired'], dtype='<U10'),
 array([ 8,  9,  8, 14, 10]))

In [17]:
##Does the step_count with modd;

##count dayS WHERE MOOOD was happy
import numpy as np
np.mean(steps[mood == 'happy'])



np.float64(8284.444444444445)

In [18]:
np.unique(mood[steps > 4000], return_counts=True)

(array(['energetic', 'happy', 'sad', 'stressed', 'tired'], dtype='<U10'),
 array([ 7,  8,  5, 11,  9]))

## Image Manipulation

In [20]:
##operaton on array in numpy
ml = np.arange(12).reshape(3,4)
ml

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
ml + 2 ##gets added to every elelemt in ml

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [24]:
a = np.array([1,2,3])
b = np.array([3,4,5])
a + b

array([4, 6, 8])

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(3,4)

b = b.reshape(4,3)
b

np.matmul(a,b) ##for matrix multiplicaion in numpy

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [34]:
np.dot(b,a)
np.dot(a,b)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [35]:
##dot producta
a = np.array([1,2,3])
b = np.array([1,1,1])
np.dot(a,b)

np.int64(6)

In [36]:
A = np.arange(12).reshape(3,4)

In [ ]:
A * 2 ##this is a vectorised fucntions

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
##universal funcs provided by numpy


import math
np_log = np.vectorize(math.log)

In [41]:
np_log([10,100,1000])

array([2.30258509, 4.60517019, 6.90775528])

In [8]:
py -m pip install --upgrade pip


SyntaxError: invalid syntax (2214374433.py, line 1)

In [10]:
pip install matplotlib

  Using cached matplotlib-3.11.0-cp314-cp314-win_amd64.whl.metadata (80 kB)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
  Using cached pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Using cached matplotlib-3.11.0-cp314-cp314-win_amd64.whl (9.5 MB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Using cached pillow-12.2.0-cp314-cp314-win_amd64.whl (7.2 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)

   ----- ---------------------------------- 1/7 [pillow]
   ----

In [ ]:
import numpy as np
import math
import matplotlib.pyplot as plt

# x = np.arange(1,101)
# y = np.vectorize(math.log)(x)  ##what vectorise does it applies this log fucntion to evry elemet of x

# plt.plot(x,y)
# plt.show()

x =  np.array([1,2,3])
y = np.vectorize(math.sqrt)(x)
y



array([1.        , 1.41421356, 1.73205081])

In [49]:
##new axis -- add new dimenestion to the numoy array
# a = np.array([1,2,3])
# a.shape
# aa = a[np.newaxis,:]
# aa.shape
# aaa = a[:,np.newaxis]
# aaa

a = np.array([1,2,3])
a
#aa = a[np.newaxis,:]
aa = a[:,np.newaxis]
aa


array([[1],
       [2],
       [3]])

## Broadcasting


In [20]:
##repating behavavour
##tile ka kaam hota hi repeat kran

A = np.tile(np.arange(0,40,10),(3,1))
print(A)
A =  A.T
A
# A = np.tile(np.arange(0,40,10),(3,1))  ##epeating array acroos vertical deminsion 3 times
# A = A.T
# A

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b = np.array([0,1,2]) ##ye vectorise ho jata hai or plus ho jata hai
A + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [9]:
a = np.arange(1,40,10).reshape(4,1)
print(a)
b = np.array([1,2,3])
a * b

[[ 1]
 [11]
 [21]
 [31]]


array([[ 1,  2,  3],
       [11, 22, 33],
       [21, 42, 63],
       [31, 62, 93]])

In [ ]:
## when Broadcasting wont work == (3,4)(1,3)


In [ ]:
## @ -- is used for matrix multiplication, this is equvalent to matmul
##

# a = np.array([[1,2],[3,4]])
# b = np.array([[5,6],[7,8]])
# np.matmul(a,b)


# a = np.array([1,2,3])
# b = np.array([1,2,3])
# print(a@b)


14


In [ ]:
##boardcasting works when-
## one of the dimension match, and the other is 1
## 

In [2]:
import numpy as np
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [5]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
x = np.arange(16).reshape(4,4)

xx = np.split(x,4,axis=1) ##spliting, axis 1 mtln horizontally
xx

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:

xxx = np.hstack(xx) ##joiningarray
xxx

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
x = np.array([1,2])
y = np.array([3,4])
np.hstack((x,y))

array([1, 2, 3, 4])

In [ ]:
### #d array -- (page, row, col)
x = np.arange(8).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
## index 
# x[pagestart:pageend,row:end,col:end]
x[:,0,:]

array([[0, 1],
       [4, 5]])

In [ ]:
a = np.array([0,1,2])
id(a) ##id tells address in ram

2906898172400