### Universal Functions

In [ ]:
##Universal functions
##vectorised fuctios
##Agregate function
#Logical functions


In [ ]:
import numpy as np

###agretate and reduction functions

In [3]:
a = np.array([1,2])
b = np.array([1,2])
a+b

array([2, 4])

In [9]:
a = np.arange(12).reshape(3,4)
print(a)
# np.sum(a)

##calculation the sum in different dimensions, accorss the row, col etss
a.shape ##it says across first dimension it has 3 elkeemts and 2nd dimension we have 4 elements


#exmpale sum in cols wise
np.sum(a,axis=0) ##sum is happening 0 axis downwords direction
np.sum(a,axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [12]:
np.mean(a,axis=1)
np.min(a,axis=0)

array([0, 1, 2, 3])

In [ ]:
###Logical Functions:
a = np.array([0,0]) ##return true if any number is non zero
np.any(a)


np.False_

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
a<b

np.any(a<b) ##kya koi esa no hai jo is conf=diton ko true karta hia

np.True_

In [ ]:
a = np.array([1,2,1,0])
b = np.array([4,3,2,1])
np.all(a<b)  

##we use & in numpy becoz it is written in c


np.True_

In [ ]:
##sorting fucntions:::

a = np.array([1,4,7,3,6,9])
np.sort(a)
np.argsort(a) ##returns indexxx


array([0, 3, 1, 4, 2, 5])

In [27]:
a = np.array([[1,4,6],[7,5,8],[6,8,7]]) ##by deaults it get sorted in last dimentsion wchih is 1
np.sort(a)

array([[1, 4, 6],
       [5, 7, 8],
       [6, 7, 8]])

In [30]:
pip install pandas

  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.9 MB 3.5 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 4.4 MB/s eta 0:00:02
   -------------- ------------------------- 3.7/9.9 MB 5.5 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 5.9 MB/s eta 0:00:01
   -------------------------- ------------- 6.6/9.9 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/9.9 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 6.2 MB/s  0:00:01

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   --------------

In [148]:
import numpy as np
h = np.loadtxt('../steps_tracker_dataset (1).txt',dtype="str",skiprows=1)
print(h)

[['08/10/2022' '4147' '3.11' '124.41' '41' '10.5' '3.77' 'stressed']
 ['11/06/2022' '323' '0.24' '9.69' '3' '6' '1.9' 'sad']
 ['28/01/2022' '6622' '4.97' '198.66' '66' '6' '4.48' 'sad']
 ['23/03/2022' '11136' '8.35' '334.08' '111' '8' '1.08' 'tired']
 ['20/05/2022' '2718' '2.04' '81.54' '27' '4.9' '1' 'tired']
 ['26/12/2022' '4972' '3.73' '149.16' '50' '6' '3.33' 'happy']
 ['27/07/2022' '15271' '11.45' '458.13' '153' '3.4' '0.88' 'happy']
 ['13/07/2022' '17290' '12.97' '518.7' '173' '11.6' '4.08' 'energetic']
 ['17/06/2022' '1042' '0.78' '31.26' '10' '6.5' '2.49' 'happy']
 ['25/06/2022' '6818' '5.11' '204.54' '68' '6.5' '3.61' 'stressed']
 ['16/01/2022' '13141' '9.86' '394.23' '131' '6.5' '2.35' 'tired']
 ['16/06/2022' '5046' '3.78' '151.38' '50' '6' '4.03' 'happy']
 ['30/10/2022' '11615' '8.71' '348.45' '116' '7.8' '0.43' 'stressed']
 ['22/08/2022' '4301' '3.23' '129.03' '43' '9' '2.87' 'happy']
 ['22/07/2022' '8655' '6.49' '259.65' '87' '9' '0.94' 'happy']
 ['08/09/2022' '14113' '10.

In [94]:
h.ndim

2

In [95]:
h.shape

(49, 8)

In [149]:
##extract coloumns
h.T[0]



array(['08/10/2022', '11/06/2022', '28/01/2022', '23/03/2022',
       '20/05/2022', '26/12/2022', '27/07/2022', '13/07/2022',
       '17/06/2022', '25/06/2022', '16/01/2022', '16/06/2022',
       '30/10/2022', '22/08/2022', '22/07/2022', '08/09/2022',
       '09/07/2022', '04/04/2022', '26/01/2022', '24/01/2022',
       '28/07/2022', '09/02/2022', '06/08/2022', '31/10/2022',
       '26/03/2022', '19/05/2022', '10/05/2022', '13/05/2022',
       '13/06/2022', '24/07/2022', '01/02/2022', '23/01/2022',
       '08/05/2022', '07/03/2022', '20/08/2022', '20/09/2022',
       '01/08/2022', '26/07/2022', '07/07/2022', '23/01/2022',
       '17/08/2022', '01/03/2022', '22/04/2022', '14/12/2022',
       '03/03/2022', '21/05/2022', '11/01/2022', '06/03/2022',
       '29/08/2022'], dtype='<U10')

In [150]:
date,steps,distance_km,calories_burned,active_minutes,sleep_hours,water_intake_liters,mood = h.T


In [151]:
print(mood)

['stressed' 'sad' 'sad' 'tired' 'tired' 'happy' 'happy' 'energetic'
 'happy' 'stressed' 'tired' 'happy' 'stressed' 'happy' 'happy' 'stressed'
 'energetic' 'sad' 'stressed' 'sad' 'happy' 'energetic' 'tired' 'stressed'
 'sad' 'energetic' 'sad' 'stressed' 'sad' 'happy' 'stressed' 'stressed'
 'energetic' 'stressed' 'tired' 'tired' 'sad' 'tired' 'tired' 'stressed'
 'stressed' 'energetic' 'energetic' 'tired' 'happy' 'tired' 'energetic'
 'stressed' 'stressed']


In [157]:
calories_burned = np.array(calories_burned).astype(float)
sleep_hours = np.array(sleep_hours, dtype='float')
water_intake_liters = np.array(water_intake_liters, dtype='float')
distance_km = np.array(distance_km,dtype='float')
active_minutes = np.array(active_minutes).astype(int)
steps = np.array(steps).astype(int)
mood = np.array(mood).astype(str)

In [158]:
print(steps_distance_km)

[ 4147   323  6622 11136  2718  4972 15271 17290  1042  6818 13141  5046
 11615  4301  8655 14113 15435 18451 11850  1075  5340 13972 17002  7786
 10776 15203  2644  1905  7467 15005  1811 17812  1193 14118 17536  8159
 16123  5606  6292  7740  8678  5861 10948 11079 14928 19940 10598 17134
  3276 17751  6679  8929   329 17094  1964 19702 13813  6169 11000  6683
   843  5397 12976  2169  7287 10720   765 18989  3105  7445 15063  1505
 18313 13681 17964  8497 17993 19143 19529  1683 14008 10941  6220 19260
  4237 16177  5179 17215 15893  8761 14137 19389 12523  2005 18641 15534
 11182  5966 16126  7321 15413 19181  1462  8899  2576  5636 12806  4016
  3969   524  2119 10678  4053  3187 19309 10368  8613 10193  5357  2382
  6208 10549   816 18194  8905 18329  7115  4029 16227  7714  2080 11990
 15730  8853 15433 17380   470  6791 15059 13822  7398 11801  4896 14635
   630  4804 18922  3859 14219 11151  6482  1349  5071   817  4797  4487
   976 10183 16103 11848 10499 12612 12150 16810 12

In [159]:
np.unique(mood)

array(['energetic', 'happy', 'sad', 'stressed', 'tired'], dtype='<U10')

In [160]:
##replacing numbers with string
# mood[mood == 'energetic'] = 300
# mood[mood == 'happy'] = 200
# mood[mood == 'sad'] = 100
# mood[mood == 'tired'] = 50
# mood[mood == 'stressed'] = 10
mood


array(['stressed', 'sad', 'sad', 'tired', 'tired', 'happy', 'happy',
       'energetic', 'happy', 'stressed', 'tired', 'happy', 'stressed',
       'happy', 'happy', 'stressed', 'energetic', 'sad', 'stressed',
       'sad', 'happy', 'energetic', 'tired', 'stressed', 'sad',
       'energetic', 'sad', 'stressed', 'sad', 'happy', 'stressed',
       'stressed', 'energetic', 'stressed', 'tired', 'tired', 'sad',
       'tired', 'tired', 'stressed', 'stressed', 'energetic', 'energetic',
       'tired', 'happy', 'tired', 'energetic', 'stressed', 'stressed'],
      dtype='<U10')

In [113]:
active_minutes[active_minutes < 100] = '0'
active_minutes[active_minutes >= 100] = '1'
active_minutes


array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0])

In [118]:
np.mean(steps)

np.float64(9590.877551020409)

In [145]:
# intmx = np.max(steps)

# for i in range(len(steps)):
#     for i in range(len(date)):
#         if steps[i] == intmx:
#            print(date[i])


max_steps = np.argmax(steps)
ans = date[max_steps]
print(ans)



21/05/2022


In [ ]:
##what is the most frequent mood.
len(mood[mood == 'happy'])



9

In [165]:
np.unique(mood,return_counts=True)

(array(['energetic', 'happy', 'sad', 'stressed', 'tired'], dtype='<U10'),
 array([ 8,  9,  8, 14, 10]))